export enum Area {
  DIRECCION = "DIRECCION",
  RECURSOS_HUMANOS = "RECURSOS_HUMANOS",
  FINANZAS = "FINANZAS",
  CONTABILIDAD = "CONTABILIDAD",
  PRODUCCION_Y_OPERACIONES = "PRODUCCION_Y_OPERACIONES",
  MARKETING_Y_VENTAS = "MARKETING_Y_VENTAS",
  LOGISTICA = "LOGISTICA",
  INVESTIGACION_Y_DESARROLLO = "INVESTIGACION_Y_DESARROLLO",
}
