export enum BadgeTypeEnum {
  ECOAHORRO = "ECOAHORRO",
  RECICLADOR = "RECICLADOR",
  MOVILIDAD_VERDE = "MOVILIDAD_VERDE",
  CONSUMO_CONSCIENTE = "CONSUMO_CONSCIENTE",
  HUELLA_ZERO = "HUELLA_ZERO",
  PROTECTOR_DEL_AGUA = "PROTECTOR_DEL_AGUA",
  EMBAJADOR_VERDE = "EMBAJADOR_VERDE",
}
