export enum EcoCategoryEnum {
  ENERGY_EFFICIENCY = "ENERGY_EFFICIENCY",
  WASTE_MANAGEMENT = "WASTE_MANAGEMENT",
  SUSTAINABLE_MOBILITY = "SUSTAINABLE_MOBILITY",
  RESPONSIBLE_CONSUMPTION = "RESPONSIBLE_CONSUMPTION",
  WATER_CONSERVATION = "WATER_CONSERVATION",
  CARBON_FOOTPRINT = "CARBON_FOOTPRINT",
}
