export enum LessonTypeEnum {
  EFICIENCIA_ENERGETICA = "EFICIENCIA_ENERGETICA",
  GESTION_DE_RESIDUOS = "GESTION_DE_RESIDUOS",
  MOVILIDAD_SOSTENIBLE = "MOVILIDAD_SOSTENIBLE",
  CONSUMO_RESPONSABLE = "CONSUMO_RESPONSABLE",
  HUELLA_DE_CARBONO = "HUELLA_DE_CARBONO",
  ECONOMIA_CIRCULAR = "ECONOMIA_CIRCULAR",
  AGUA_Y_BIODIVERSIDAD = "AGUA_Y_BIODIVERSIDAD",
  POLITICAS_AMBIENTALES = "POLITICAS_AMBIENTALES",
  TECNOLOGIAS_VERDES = "TECNOLOGIAS_VERDES",
  CULTURA_SOSTENIBLE = "CULTURA_SOSTENIBLE",
}
