export enum TaskTypeEnum {
  APAGAR_EQUIPOS = "APAGAR_EQUIPOS",
  RECICLAJE = "RECICLAJE",
  MOVILIDAD_SOSTENIBLE = "MOVILIDAD_SOSTENIBLE",
  USO_REUTILIZABLES = "USO_REUTILIZABLES",
  AHORRO_AGUA = "AHORRO_AGUA",
  COMPENSACION_CO2 = "COMPENSACION_CO2",
  EFICIENCIA_ENERGETICA = "EFICIENCIA_ENERGETICA",
  CAPACITACION_AMBIENTAL = "CAPACITACION_AMBIENTAL",
  VOLUNTARIADO_AMBIENTAL = "VOLUNTARIADO_AMBIENTAL",
}
