import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1 },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingTop: 60,
        paddingBottom: 24,
    },
    backIcon: { fontSize: 24 },
    title: { fontSize: 20, fontWeight: '700' },
    content: { flex: 1 },
    section: { paddingHorizontal: 24, marginBottom: 32 },
    sectionTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 16 },
    inputGroup: { marginBottom: 16 },
    inputLabel: { fontSize: 16, fontWeight: '600', marginBottom: 8 },
    input: { textAlignVertical: 'center' },
    categoriesGrid: {
        flexDirection: 'column',
        gap: 15,
    },
    categoryOption: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 12,
        borderWidth: 1,
        minWidth: '30%',
        alignItems: 'center',
    },
    categoryOptionText: { fontSize: 14, fontWeight: '500' },
    difficultiesRow: { flexDirection: 'row', gap: 12 },
    difficultyOption: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 12,
        borderWidth: 1,
        alignItems: 'center',
    },
    difficultyText: { fontSize: 14, fontWeight: '600' },
    iconsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    iconOption: {
        width: 50,
        height: 50,
        borderRadius: 25,
        borderWidth: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    iconText: { fontSize: 20 },
    previewCard: {
        padding: 20,
        borderRadius: 16,
        borderWidth: 1,
    },
    previewHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    previewIcon: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#f3f4f6',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    previewIconText: { fontSize: 20 },
    previewInfo: { flex: 1 },
    previewTitle: { fontSize: 16, fontWeight: '700', marginBottom: 4 },
    previewCategory: { fontSize: 14, marginBottom: 6, opacity: 0.8 },
    previewMeta: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    previewDifficulty: {
        fontSize: 10,
        fontWeight: '600',
        color: 'white',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 8,
    },
    previewDuration: { fontSize: 12, opacity: 0.7 },
    previewXP: { fontSize: 12, opacity: 0.7 },
    previewDescription: {
        fontSize: 14,
        lineHeight: 20,
        opacity: 0.8,
    },
    buttonsContainer: {
        paddingHorizontal: 24,
        paddingBottom: 32,
        gap: 12,
    },
    submitButton: { marginBottom: 8 },
    cancelButton: { marginBottom: 8 },
});